dynaconf_merge = true
[default]

db.user = "postgres"
db.password = "postgres"
db.host = "0.0.0.0"
db.port = 5432
db.db_name = "postgres"

redis.host = "0.0.0.0"
redis.port = 6379
redis.db = 1
redis.password = ""

UPLOAD_FILE_LIMIT = 10485760  # 10 megabyte
VALID_EXTENSIONS = ["csv"]

[docker]
db.host = "postgres"
db.user = "postgres"
db.password = "postgres"
db.port = 5432
db.db_name = "test"

redis.host = "redis"
redis.port = 6379
redis.db = 1
redis.password = ""
